services:
  web:
    container_name: web
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    networks:
      - my_network

  cron:
    container_name: cron
    image: alpine/curl
    command: >
      sh -c "
        echo '*/10 * * * * curl -X POST http://web:3000/db/clear' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - web
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
